In [1]:
import numpy as np

**The Basics**

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1.0, 2.0, 3.5], [4.7, 5.1, 6.6]])
print(b)

[[1.  2.  3.5]
 [4.7 5.1 6.6]]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
b.ndim

2

In [7]:
# Get shape
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [10]:
# Get type 
a.dtype

dtype('int32')

In [11]:
# Get size of individual elements
a.itemsize

4

In [12]:
# Get total size
a.itemsize * a.size

12

In [13]:
# Get total size
a.nbytes

12

### Accessing/Changing specific elements, rows, columns, etc

In [33]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
# Get a specific element [r, c]
a[0, 4]

5

In [23]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
# Get a specific column
a[:, 1]

array([2, 9])

In [28]:
# Get column 1,2,3
a[:, 1:4:1]

array([[ 2,  3,  4],
       [ 9, 10, 11]])

In [30]:
# Replace a[1,5] value with 20
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [34]:
# Replace entire second row with 0's
a[1, :] = 0
print(a)

[[1 2 3 4 5 6 7]
 [0 0 0 0 0 0 0]]


In [39]:
# 3D array
b = np.array([[[1, 2],[3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
# Get specific 3D element

b[0, 1, 1]

4

In [40]:
# Replace first row of every 2D matrix
b[:, 0, :] = 0
print(b)

[[[0 0]
  [3 4]]

 [[0 0]
  [7 8]]]


### Initializing Different Types of Arrays

In [41]:
# All 0s matrix
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
# All 1s matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
# All any-other-number matrix
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [46]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.11910656, 0.450627  ],
       [0.62758568, 0.34808036],
       [0.1707781 , 0.95830659],
       [0.6539457 , 0.30973381]])

In [48]:
# Random decimal numbders
np.random.random_sample(a.shape)

array([[0.69414915, 0.08122666, 0.84130491, 0.62009104, 0.39951268,
        0.48584867, 0.30945667],
       [0.71997303, 0.22936968, 0.75269456, 0.59717021, 0.31486201,
        0.96918106, 0.17107313]])

In [60]:
# Random Integer values
np.random.randint(low=3, high=6, size=(3,3))

array([[5, 5, 4],
       [4, 3, 3],
       [3, 3, 5]])

In [61]:
# Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
# Repeat
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [71]:
# Practice

practice_array = np.ones((5,5))
practice_array[1:4, 1:4] = 0
practice_array[2, 2] = 9
print(practice_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [72]:
# Copying arrays
a = np.array([1,2,3])
b = a
print(b)

[1 2 3]


In [74]:
b[0] = 100
print(b)

[100   2   3]


In [75]:
print(a)

[100   2   3]


In [76]:
# Correct way of copying
b = a.copy()

### Mathematics 

In [77]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [78]:
# Element wise operations
a + 2

array([3, 4, 5, 6])

In [79]:
a + 1

array([2, 3, 4, 5])

In [80]:
a * 3

array([ 3,  6,  9, 12])

In [81]:
a += 2

In [82]:
a

array([3, 4, 5, 6])

In [83]:
a + 2

array([5, 6, 7, 8])

In [84]:
a ** 2

array([ 9, 16, 25, 36], dtype=int32)

In [85]:
# Take the sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

### Linear Algebra

In [86]:
a = np.full((2,3), 1)

In [87]:
b = np.full((3,2), 2)

In [88]:
np.matmul(a, b)

array([[6, 6],
       [6, 6]])

In [89]:
c = np.identity(3)

In [91]:
# Find the determinant
np.linalg.det(c)

1.0

### Statistics 

In [93]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
np.min(stats, axis = 1)

array([1, 4])

In [97]:
np.max(stats, axis = 1)

array([3, 6])

### Reorganizing Arrays

In [98]:
before = np.array([[1,2,3,4], [5, 6, 7, 8]])

In [101]:
after = before.reshape((4,2))

In [102]:
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [104]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [105]:
# Horizontal stack

np.hstack([v1, v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [126]:
# Load Data from File
filedata = np.genfromtxt("a1.txt", delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[ 1  2  3  4  5  6  7  8]
 [ 4  5  6  7  8  9 10 11]]


### Boolean Masking and Advanced Indexing

In [114]:
filedata >= 10

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True,  True]])

In [117]:
filedata[filedata > 5].astype('int32')

array([ 6,  7,  8,  6,  7,  8,  9, 10, 11])

In [121]:
a = np.array([1, 2, 3, 4, 5, 6])
a[[0]]

array([1])

In [125]:
# Check if column has all values greater than 5

np.all(filedata > 5, axis = 0)

array([False, False, False, False, False,  True,  True,  True])

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11.]])