In [1]:
import numpy as np

**The Basics**

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1.0, 2.0, 3.5], [4.7, 5.1, 6.6]])
print(b)

[[1.  2.  3.5]
 [4.7 5.1 6.6]]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
b.ndim

2

In [7]:
# Get shape
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [10]:
# Get type 
a.dtype

dtype('int32')

In [11]:
# Get size of individual elements
a.itemsize

4

In [12]:
# Get total size
a.itemsize * a.size

12

In [13]:
# Get total size
a.nbytes

12

### Accessing/Changing specific elements, rows, columns, etc

In [33]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
# Get a specific element [r, c]
a[0, 4]

5

In [23]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
# Get a specific column
a[:, 1]

array([2, 9])

In [28]:
# Get column 1,2,3
a[:, 1:4:1]

array([[ 2,  3,  4],
       [ 9, 10, 11]])

In [30]:
# Replace a[1,5] value with 20
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [34]:
# Replace entire second row with 0's
a[1, :] = 0
print(a)

[[1 2 3 4 5 6 7]
 [0 0 0 0 0 0 0]]
